workflow_email_template.notifications.*:
  type: config_entity
  label: 'Notifications config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
